version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build-api
    depends_on:
      - postgres
    volumes:
      - .:/src
  
  metabase:
    image: metabase/metabase:latest
    ports:
      - "12345:3000"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

